# Generated by Django 5.1.4 on 2025-04-11 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ersathi', '0030_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='stripe_account_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='stripe_account_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('restricted', 'Restricted')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='booking_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
