# Generated by Django 5.1.4 on 2025-04-12 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ersathi', '0031_company_stripe_account_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AddField(
            model_name='order',
            name='buying_status',
            field=models.CharField(blank=True, choices=[('paid', 'Paid'), ('processing', 'Processing'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='renting_status',
            field=models.CharField(blank=True, choices=[('booked', 'Booked'), ('picked up', 'Picked Up'), ('returned', 'Returned'), ('cancelled', 'Cancelled')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('buying', 'Buying'), ('renting', 'Renting'), ('mixed', 'Mixed')], max_length=20),
        ),
    ]
