# Generated by Django 5.1.4 on 2025-04-12 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ersathi', '0032_remove_order_status_order_buying_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='item_type',
            field=models.CharField(blank=True, choices=[('buying', 'Buying'), ('renting', 'Renting')], max_length=20, null=True),
        ),
    ]
