# Generated by Django 5.1.4 on 2025-04-12 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ersathi', '0033_orderitem_item_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='company',
        ),
    ]
