# Generated by Django 5.1.4 on 2025-04-13 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ersathi', '0034_remove_order_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='payment_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
