# Generated by Django 5.1.4 on 2025-04-14 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ersathi', '0036_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='grace_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='trial_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
