# Generated by Django 5.1.4 on 2025-04-14 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ersathi', '0037_subscription_grace_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='has_used_trial',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.CharField(choices=[('trial', 'Trial'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=20),
        ),
    ]
