# Generated by Django 5.1.4 on 2025-04-23 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ersathi', '0040_company_customuser_alter_customuser_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingconstructiondata',
            name='construction_phase',
            field=models.CharField(blank=True, choices=[('Foundation', 'Foundation'), ('Walls', 'Walls'), ('Finishing', 'Finishing'), ('Excavation', 'Excavation '), ('Columns Casting', 'Columns Casting'), ('Beams Casting', 'Beams Casting'), ('Slab Casting', 'Slab Casting'), ('Roofing', 'Roofing'), ('Electrical & Plumbing', 'Electrical & Plumbing'), ('Plastering', 'Plastering'), ('Finishing', 'Finishing')], max_length=50, null=True),
        ),
    ]
