# Generated by Django 5.1.4 on 2025-05-01 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ersathi', '0045_remove_chatmessage_channel_remove_chatmessage_sender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='company_registration_id',
        ),
        migrations.AddField(
            model_name='company',
            name='registration_certificate',
            field=models.FileField(blank=True, null=True, upload_to='company_certificates/'),
        ),
    ]
