# Generated by Django 5.1.4 on 2025-05-01 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ersathi', '0046_remove_company_company_registration_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_type',
            field=models.CharField(choices=[('construction', 'Construction Company'), ('supplier', 'Material Supplier')], max_length=50),
        ),
    ]
