# Generated by Django 5.1.4 on 2025-05-03 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ersathi', '0049_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='purpose',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
