# Generated by Django 5.1.4 on 2025-05-03 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ersathi', '0050_payment_purpose'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='transaction_id',
        ),
    ]
