# Generated by Django 5.1.4 on 2025-05-09 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ersathi', '0051_remove_payment_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='num_reviews',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
