# Generated by Django 5.1.4 on 2025-05-10 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ersathi', '0054_product_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deadline_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='fine_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
