# Generated by Django 5.1.4 on 2025-05-10 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ersathi', '0055_order_deadline_date_order_fine_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='deadline_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='fine_amount',
        ),
    ]
