# Generated by Django 5.1.4 on 2025-05-18 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ersathi', '0057_alter_engineeringconsultingdata_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender_company',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender_user',
        ),
        migrations.AddField(
            model_name='product',
            name='threshold',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
