# Generated by Django 5.1.4 on 2025-05-23 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ersathi', '0059_chatroom_remove_product_threshold_chatrequest_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='chat_room',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='user',
        ),
        migrations.RemoveField(
            model_name='chatrequest',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='chatrequest',
            name='sender',
        ),
        migrations.DeleteModel(
            name='ChatRoom',
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.DeleteModel(
            name='ChatRequest',
        ),
    ]
