# Generated by Django 5.1.4 on 2025-05-23 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ersathi', '0061_complaint_supportrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
