# Generated by Django 5.1.4 on 2025-05-23 23:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ersathi', '0062_complaint_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='category',
            field=models.CharField(choices=[('Service Quality', 'Service Quality'), ('Payment Issue', 'Payment Issue'), ('Technical Problem', 'Technical Problem'), ('Other', 'Other')], help_text='Category of the complaint.', max_length=50),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the complaint was created.'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='description',
            field=models.TextField(help_text='Detailed description of the complaint.'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='email',
            field=models.EmailField(blank=True, help_text='Email for anonymous submissions.', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='subject',
            field=models.CharField(help_text='Subject of the complaint.', max_length=200),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='user',
            field=models.ForeignKey(blank=True, help_text='The user who submitted the complaint, if authenticated.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='supportrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the request was created.'),
        ),
        migrations.AlterField(
            model_name='supportrequest',
            name='email',
            field=models.EmailField(help_text='Email address for contact.', max_length=254),
        ),
        migrations.AlterField(
            model_name='supportrequest',
            name='message',
            field=models.TextField(help_text='Detailed message of the support request.'),
        ),
        migrations.AlterField(
            model_name='supportrequest',
            name='name',
            field=models.CharField(help_text='Name of the submitter.', max_length=100),
        ),
        migrations.AlterField(
            model_name='supportrequest',
            name='subject',
            field=models.CharField(help_text='Subject of the support request.', max_length=200),
        ),
        migrations.AlterField(
            model_name='supportrequest',
            name='user',
            field=models.ForeignKey(blank=True, help_text='The user who submitted the support request, if authenticated.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='support_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['created_at'], name='ersathi_com_created_f29f29_idx'),
        ),
        migrations.AddIndex(
            model_name='supportrequest',
            index=models.Index(fields=['created_at'], name='ersathi_sup_created_43dce8_idx'),
        ),
    ]
